lattice info:
  nx: 48
  ny: 48
  nz: 48
  nt: 144
  u0: 1.0
  wpnorm: 3
  ncolor: 3
  ens: l48144f211b672m0048m024m286a
  cfg_dir: /rds/project/dirac_vol4/rds-dirac-dp019/confs/l48144f211b672m0048m024m286a
  max_cg_iterations: 1000
  max_cg_restarts: 3
  precision: 2
  nsrc: 8             # Number of source times 
  allsources: True     # True if you want to run all sources, else [0,2,3] eg to skip the second of 4
  nsrcdivider: 6       #This is the denominator in the source start determination. Usually 5 or 6.	 
  tag: tTphasetest-           #Tag go on front of saved versions
  justtwopoints: False
  submit: ./submit/submit_ks_spectrum_hisq.slurm-skylake
#props (all of them)

parent prop:
  quark: heavy                                          # 'heavy', 'charm', 'strange', 'light'
  name: B
  masses:
  - '0.274'
  - '0.450'
  - '0.6'
  - '0.8'
  twist: '0'
  spin_taste:
  - GY-GY
  error: 0
  rel_error: 6e-14
  multimass: True                                           #Do you want to use a multimass inverter, ie group together in one set


daughter prop:
  quark: strange
  name: K
  mass: '0.0376'
  twists:
  - '0'
  spin_taste:    
  - G5-G5         # List of all spin tastes
  error: 1e-8
  rel_error: 0
  save: False      # Will not save props which are loaded. Currently only saves G5-G5
  

spectator prop:   # Put this in even if it is the same as one of the daughter props
  quark: strange
  same: True      # Is this the same as a daughter prop?
  load: True
  check: yes      
  mass: '0.0376'
  twist: '0'           
  error: 1e-8
  rel_error: 0
  save: False
  load_directory: /home/dc-parr2/rds/rds-dirac-dp019/Esther/props/{0}.{1}_wallprop_m{3}_t{2} #set up so can be followed by .format(ens,cfg,t0,mass)

# Daughter props we want to load (these should appear in daughter prop too )

daughter load:
  check: yes        # yes or no on checking the loaded file
  twists:
  - '0'
#  - '0.4281'
#  - '1.282'
#  - '2.141'
#  - '2.570'
  spin_taste:
  - G5-G5             # assume G5-G5 for sources, but write once for each twist appearing
#  - G5-G5
#  - G5-G5
#  - G5-G5
#  - G5-G5 
  load_directory:
  - /home/dc-parr2/rds/rds-dirac-dp019/Esther/props/{0}.{1}_wallprop_m{3}_t{2} #set up so can be followed by .format(ens,cfg,t0,mass,twist)
#  - /home/dc-parr2/rds/rds-dirac-dp019/Will/BsEtas/fine/th0.4281/{0}.{1}_wallprop_m{3}_th{4}_t{2}
#  - /home/dc-parr2/rds/rds-dirac-dp019/propagators/fine5/th1.282/{0}.{1}_wallprop_m{3}_th{4}_t{2}
#  - /home/dc-parr2/rds/rds-dirac-dp019/Will/BsEtas/fine/th2.1410/{0}.{1}_wallprop_m{3}_th{4}_t{2}
#  - /home/dc-parr2/rds/rds-dirac-dp019/Will/BsEtas/fine/th2.570/{0}.{1}_wallprop_m{3}_th{4}_t{2}

# Existing (daughter-spectator) Corrs for which we don't want 2 point functions. We assume we have the props for these. If we do not, then we will need to run them for the 3 points so may as well regenerate the 2 points now. 

#daughter existing:
#  mass: '0.0376'
#  twists:
#  - '0'
#  - '0.4281'
#  - '1.282'
#  - '2.141'
#  - '2.57'
#  spin_taste:
#  - G5-G5
#  - G5-G5
#  - G5-G5
#  - G5-G5
#  - G5-G5


# Three points

three points:
  nT: 3
  dT: 5
  Tstart: 20
  p J d:                       # Parent, current and daughter spin taste combinations
  - G5-G5 G1-G1 G5-G5
  - G5T-G5T GT-GT G5-G5
  - G5T-G5T GXT-GXT G5-G5X
  label:              # labels for the file names of the above ie "scalar" will be put in corrs/current-scalar_tw{0}.format(twist)
  - scalar                    
  - vector
  - tensor