lattice info:
  nx: 16
  ny: 16
  nz: 16
  nt: 48
  u0: 1.0
  wpnorm: 3
  ncolor: 3
  ens: l1648f211b580m013m065m838a
  cfg_dir: /rds/project/dirac_vol4/rds-dirac-dp019/confs/l1648f211b580m013m065m838/l1648f211b580m013m065m838a
  max_cg_iterations: 1000
  max_cg_restarts: 3
  precision: 2
  nsrc: 4             # Number of source times 
  nsrcdivider: 5       #This is the denominator in the source start determination. Usually 5 or 6.	 
  tag: test-           #Tag go on front of saved versions
  justtwopoints: False
  submit: ./submit/submit_ks_spectrum_hisq.slurm-skylake
#props (all of them)

parent prop:
  name: B
  masses:
  - 0.194
  - 0.45
  #- 0.6
  #- 0.8
  twist: 0
  spin_taste:
  - G5-G5
  - G5T-G5T
  error: 0
  rel_error: 6e-14
  multimass: False                                           #Do you want to use a multimass inverter, ie group together in one set


daughter prop:
  name: K
  mass: 0.065
  twists:
  - 0
  - 0.706
  #- 1.529
  #- 2.235
  #- 4.705
  spin_taste:    
  - G5-G5         # List of all spin tastes
  - G5-G5X
  error: 1e-8
  rel_error: 0
  save: False      # Will not save props which are loaded. Currently only saves G5-G5

spectator prop:   # Put this in even if it is the same as one of the daughter props
  same: False      # Is this the same as a daughter prop?
  load: False
  check: yes      
  mass: 0.013
  twist: 0           
  error: 1e-8
  rel_error: 0
  save: False
  load_directory: /home/dc-parr2/rds/rds-dirac-dp019/Will/fine/props-links/{0}.{1}_wallprop_m{3}_t{2} #set up so can be followed by .format(ens,cfg,t0,mass)

# Daughter props we want to load (these should appear in daughter prop too )

#daughter load:
#  check: no        # yes or no on checking the loaded file
#  twists:
#  - 0
#  - 0.4281
#  - 1.282
#  - 2.141
#  #- 2.570
#  spin_taste:
#  - G5-G5             # assume G5-G5 for sources, but write once for each twist appearing
#  load_directory:
#  - /home/dc-parr2/rds/rds-dirac-dp019/Will/fine/props-links/{0}.{1}_wallprop_m{3}_t{2} #set up so can be followed by .format(ens,cfg,t0,mass,twist)
#  - /home/dc-parr2/rds/rds-dirac-dp019/Will/fine/props-links/{0}.{1}_wallprop_m{3}_th{4}_t{2}
#  - /home/dc-parr2/rds/rds-dirac-dp019/Will/fine/props-links/{0}.{1}_wallprop_m{3}_th{4}_t{2}
#  - /home/dc-parr2/rds/rds-dirac-dp019/Will/fine/props-links/{0}.{1}_wallprop_m{3}_th{4}_t{2}
  #- /home/dc-parr2/rds/rds-dirac-dp019/Will/fine/props-links/{0}.{1}_wallprop_m{3}_th{4}_t{2}

# Existing (daughter-spectator) Corrs for which we don't want 2 point functions. We assume we have the props for these. If we do not, then we will need to run them for the 3 points so may as well regenerate the 2 points now. 

#daughter existing:
#  mass: 0.0376
#  twists:
#  - 0
#  - 0.4281
#  - 1.282
#  - 2.141
#  - 2.570
#  spin_taste:
#  - G5-G5
#  - G5-G5
#  - G5-G5
#  - G5-G5
#  - G5-G5


# Three points

three points:
  nT: 3
  dT: 2
  Tstart: 10
  p J d:                       # Parent, current and daughter spin taste combinations
  - G5-G5 G1-G1 G5-G5
  - G5T-G5T GT-GT G5-G5
  - G5T-G5T GXT-GXT G5-G5X
  label:              # labels for the file names of the above ie "scalar" will be put in ./corrs/current-scalar_tw{0}.format(twist)
  - scalar                    
  - vector
  - tensor